logo:
  icon: /assets/geo.svg
  title: LiuZhe
  subtitle: '你怕不怕的小黑屋 | 我好怕啊'

article:
  share: [wechat, email, link]

# 侧边栏主功能导航菜单
menubar:
  columns: 3 # 一行多少个
  items: 
    - id: post
      theme: '#1BCDFC'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: explore
      theme: '#FA6400'
      icon: solar:planet-bold-duotone
      title: 探索
      url: /explore/
    - id: about
      theme: '#F44336'
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /about/

site_tree:
  home:
    rightbar: tagcloud, timeline
  index_blog:
    rightbar: tagcloud, timeline
  index_topic:
    rightbar: tagcloud, timeline
  

comment:

tag_plugins:
  image:
    fancybox: true
  quot:
    default: # 可以自行配置多种图标方案
      prefix: https://bu.dusays.com/2022/10/24/63567d3e092ff.png
      suffix: https://bu.dusays.com/2022/10/24/63567d3e0ab55.png
    hashtag:
      prefix: https://bu.dusays.com/2022/10/24/63567d3e07da3.png

style:
  prefers_theme: dark